FROM python:3.9
WORKDIR /app

COPY ./requirements.txt ./api-server-flask/api/flaskApi.py ./api-server-flask/api/.flaskenv ./
COPY ./api-server-flask/api/models.py ./api-server-flask/api/cloudSql.py ./ 
COPY ./api-server-flask/api/application_default_credentials.json ./

RUN pip install -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "flaskApi:app"]