services:
    api:
        build:
            context: .
            dockerfile: Dockerfile.api
        image: backend
        environment:
            - GOOGLE_APPLICATION_CREDENTIALS=googlecreds.json
    client:
        build:
            context: .
            dockerfile: Dockerfile.client
        image: frontend
        ports:
            - "3001:80"

