services:
    api:
        build:
            context: .
            dockerfile: Dockerfile.api
        image: react-flask-app-api
        environment:
            - GOOGLE_APPLICATION_CREDENTIALS=googlecreds.json
    client:
        build:
            context: .
            dockerfile: Dockerfile.client
        image: react-flask-app-client
        ports:
            - "3001:80"

