FROM node:18 as build-step
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./react/package.json ./react/yarn.lock ./
COPY ./react/src ./src
COPY ./react/public ./public
RUN yarn install
RUN yarn build

FROM nginx:stable-alpine
COPY --from=build-step /app/build /usr/share/nginx/html
COPY react/nginx/nginx.default.conf /etc/nginx/conf.d/default.conf