FROM python:3.9
WORKDIR /app

COPY ./requirements.txt api-server-flask/api/flaskApi.py api-server-flask/api/.flaskenv ./
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "flaskApi:app"]
